languages:
  - en
  - es
  - zh-cn
  - zh-tw
  - ar
  - fr
  - de
  - pt-br
  - tr
  - ja
  - ko

default_lang: en

# Language-specific site settings
en:
  url: "https://markleighedu.github.io"
  baseurl: "/"
  title: "Mark Leigh Educator Blog"

es:
  url: "https://markleighedu.github.io"
  baseurl: "/es"
  title: "Blog del Educador Mark Leigh"

zh-cn:
  url: "https://markleighedu.github.io"
  baseurl: "/zh-cn"
  title: "Mark Leigh 马克.李教育博客"

zh-tw:
  url: "https://markleighedu.github.io"
  baseurl: "/zh-tw"
  title: "Mark Leigh 馬克.李教育博客"

ar:
  url: "https://markleighedu.github.io"
  baseurl: "/ar"
  title: "مدونة مارك لي للمعلم"

fr:
  url: "https://markleighedu.github.io"
  baseurl: "/fr"
  title: "Blog de Mark Leigh pour les éducateurs"

de:
  url: "https://markleighedu.github.io"
  baseurl: "/de"
  title: "Mark Leigh Pädagogen-Blog"

pt-br:
  url: "https://markleighedu.github.io"
  baseurl: "/pt-br"
  title: "Blog do Educador Mark Leigh"

tr:
  url: "https://markleighedu.github.io"
  baseurl: "/tr"
  title: "Mark Leigh Eğitimci Blogu"

ja:
  url: "https://markleighedu.github.io"
  baseurl: "/ja"
  title: "Mark Leighマーク・リー教育者ブログ"

ko:
  url: "https://markleighedu.github.io"
  baseurl: "/ko"
  title: "Mark Leigh 교육자 블로그"

# Default language setting
defaults:
  - scope:
      path: ""
    values:
      lang: en

# Pagination settings
paginate: 10
paginate_path: "/:lang/page:num/"

# Ensure Jekyll processes non-English posts
include:
  - es/_posts
  - zh-cn/_posts
  - zh-tw/_posts
  - ar/_posts
  - fr/_posts
  - de/_posts
  - pt-br/_posts
  - tr/_posts
  - ja/_posts
  - ko/_posts

# Exclude unnecessary files
exclude:
  - "search.html"
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "README.zh.md"

# Jekyll Plugins
plugins:
  - jekyll-paginate

# Site settings
SEOTitle: "Mark Leigh Blog | Trading Educator | Expert Financial Insights"
email: markleigh.edu@gmail.com
description: "Mark Leigh's Personal Blog | Financial Market Trading Education"
keyword: "Mark Leigh, Educator, Education, Forex Trading, US Stock Trading"
url: "https://markleighedu.github.io/"
baseurl: ""

# Sidebar settings
sidebar: true
sidebar-about-description: "Trading Education <br> Blog @ Mark"
sidebar-avatar: "https://github.com/markleighedu.png"

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disable Disqus
disqus_username: markleigh
disable_disqus: true
