name: Delete Posts if More Than 100

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  delete-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and delete posts if more than 100
        run: |
          # Define the language directories
          LANG_DIRS=("posts/en" "posts/es" "posts/zh-cn")
          
          # Iterate through each language folder and check the number of posts
          for LANG_DIR in "${LANG_DIRS[@]}"; do
            # Count the number of posts in the language folder
            POST_COUNT=$(find $LANG_DIR -type f -name "*.md" | wc -l)
            
            # If there are more than 100 posts, delete the extra ones
            if [ "$POST_COUNT" -gt 100 ]; then
              echo "Deleting posts in $LANG_DIR as there are more than 100 posts"
              
              # Find all posts in the directory and delete them (keeping the first 100)
              POSTS_TO_DELETE=$(find $LANG_DIR -type f -name "*.md" | sort | head -n -100)
              
              # Delete the excess posts
              echo "$POSTS_TO_DELETE" | xargs rm -f

              # Commit the changes
              git add -A
              git commit -m "Deleted excess posts in $LANG_DIR"
              git push origin main
            fi
          done
